# Generated by Django 5.0.3 on 2024-03-27 00:55

import kandy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kandy', '0002_alter_application_cell_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='parent_fname',
            field=models.CharField(help_text='Required. The full name of the parrent.', max_length=50, validators=[kandy.validators.validate_f_name]),
        ),
        migrations.AlterField(
            model_name='career',
            name='f_name',
            field=models.CharField(help_text='Required. The full name of the worker.', max_length=50, validators=[kandy.validators.validate_f_name]),
        ),
    ]
