# Generated by Django 5.0.3 on 2024-03-28 15:47

import kandy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kandy', '0004_alter_application_child_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists'}, help_text='Required. Your gmail address.', max_length=254, validators=[kandy.validators.validate_email], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='career',
            name='p_number',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter a valid phone', 'unique': 'A user with that phone number already exists'}, help_text='Enter phone number e.g: +998123456789', max_length=13, null=True, unique=True, validators=[kandy.validators.PhoneValidator()], verbose_name='phone number'),
        ),
    ]
