# Generated by Django 5.0.3 on 2024-03-29 05:38

import kandy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kandy', '0006_alter_application_home_phone_alter_career_p_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='career_img',
            field=models.ImageField(blank=True, help_text='Please upload your cv or report file about your career.(.jpg, .jpeg, .png only)!', null=True, upload_to='career/'),
        ),
        migrations.AlterField(
            model_name='career',
            name='p_number',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter a valid phone'}, help_text='Enter phone number e.g: +998123456789', max_length=13, null=True, validators=[kandy.validators.PhoneValidator()], verbose_name='phone number'),
        ),
    ]
